Repository Pablo-Mdz/OLINA-webpage, pull requests merged in 2023-04, with the labels that each got.

#28 feat: add storybook to client
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/stories/Button.jsx
  client/src/stories/Button.stories.jsx
  client/src/stories/Header.jsx
  client/src/stories/Header.stories.jsx
  client/src/stories/Introduction.stories.mdx
  client/src/stories/Page.jsx
  client/src/stories/Page.stories.jsx
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: frontend

#31 refactor: add tailwind on login and sign up pages
  client/src/components/Blog/PostCard.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/SignupPage/SignupPage.jsx
Labels: frontend

#33 start with editing post
  client/src/components/Blog/CreateAPost.jsx
  client/src/components/Blog/EditPostCard.jsx
  client/src/components/Blog/Post.jsx
  client/src/components/Blog/PostCard.jsx
  client/src/components/Gallery/AddPicture.js
  client/src/components/Topic/TopicDetails.jsx
  client/src/pages/TopicPage.jsx
  server/routes/auth.routes.js
  server/routes/post.routes.js
Labels: backend, frontend, WIP(work in progress)

#58 Post style2
  client/package-lock.json
  client/package.json
  client/public/editIcon.png
  client/src/App.jsx
  client/src/components/Blog/EditPostCard.jsx
  client/src/components/Blog/PostCard.jsx
  client/src/components/Blog/SinglePost.jsx
  client/src/components/Gallery/AddPicture.jsx
  client/src/components/Topic/CreateATopic.jsx
  client/src/components/Topic/EditTopic.jsx
  client/src/components/Topic/TopicDetails.jsx
  client/src/index.css
  client/src/pages/TopicPage.jsx
  client/static/edit.png
  client/static/fonts/josefin-slab/JosefinSlab-Bold.ttf
  client/static/fonts/josefin-slab/JosefinSlab-BoldItalic.ttf
  client/static/fonts/josefin-slab/JosefinSlab-Italic.ttf
  client/static/fonts/josefin-slab/JosefinSlab-Light.ttf
  client/static/fonts/josefin-slab/JosefinSlab-LightItalic.ttf
  client/static/fonts/josefin-slab/JosefinSlab-Regular.ttf
  client/static/fonts/josefin-slab/JosefinSlab-SemiBold.ttf
  client/static/fonts/josefin-slab/JosefinSlab-SemiBoldItalic.ttf
  client/static/fonts/josefin-slab/JosefinSlab-Thin.ttf
  client/static/fonts/josefin-slab/JosefinSlab-ThinItalic.ttf
  client/static/fonts/josefin-slab/OFL.txt
  server/routes/post.routes.js
Labels: frontend

#56 add aboutMe model,routes, component
  client/src/components/AboutMe/CreateAboutMe.js
  client/src/components/AboutMe/DeleteAboutMe.jsx
  client/src/components/Gallery/DeletePicture.jsx
  client/src/images/aboutMeLogo.jpg
  client/src/pages/AboutMe/AboutMe.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  server/app.js
  server/models/AboutMe.js
  server/routes/aboutMe.routes.js
Labels: backend, frontend, WIP(work in progress)

#60 chore: move server to principal folder
  .env.example
  .gitignore
  app.js
  client/package-lock.json
  client/package.json
  config/cloudinary.js
  config/index.js
  db/index.js
  error-handling/index.js
  middleware/jwt.middleware.js
  models/AboutMe.js
  models/Gallery.js
  models/Post.js
  models/Topic.js
  models/User.js
  models/Word.js
  package.json
  prettier.config.cjs
  routes/aboutMe.routes.js
  routes/auth.routes.js
  routes/gallery.routes.js
  routes/index.routes.js
  routes/post.routes.js
  routes/topic.routes.js
  routes/word.routes.js
  server.js
  server/package-lock.json
Labels: backend

#61 refactor: Create useForm hook for form management
  client/src/hooks/useForm.js
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/SignupPage/SignupPage.jsx
Labels: frontend

#69 Not found page
  client/public/notFound.jpg
  client/src/App.jsx
  client/src/pages/NotFoundPage/NotFoundPage.jsx
  client/tailwind.config.js
  package-lock.json
Labels: frontend

#71 Refactor code using destructuring
  client/src/components/Blog/PostCard.jsx
  client/src/pages/Words/AddWords.jsx
  client/src/pages/Words/DeleteWords.jsx
  client/src/pages/Words/EditWords.jsx
  client/src/pages/Words/Words.jsx
  client/tailwind.config.js
Labels: frontend

#70 Integrate Custom Color Palette for Consistent Project Styling
  client/src/components/Blog/PostCard.jsx
  client/src/components/Blog/SinglePost.jsx
  client/src/pages/Words/ReadingTime.jsx
  client/src/pages/Words/Words.jsx
Labels: frontend

#72 Edit picture Functionality and style
  client/src/App.jsx
  client/src/components/BlogPost/CreateAPost.jsx
  client/src/components/BlogPost/EditPostCard.jsx
  client/src/components/BlogPost/PostCard.jsx
  client/src/components/BlogPost/SinglePost.jsx
  client/src/components/Gallery/AddPicture.jsx
  client/src/components/Gallery/DeletePicture.jsx
  client/src/components/Gallery/EditPicture.jsx
  client/src/components/Gallery/GalleryPage.jsx
  client/src/components/Topic/TopicDetails.jsx
  client/src/components/Topic/TopicPage.jsx
  client/src/components/Words/AddWords.jsx
  client/src/components/Words/DeleteWords.jsx
  client/src/components/Words/EditWords.jsx
  client/src/components/Words/ReadingTime.jsx
  client/src/components/Words/Words.jsx
  client/src/pages/GalleryPage.jsx
  models/Gallery.js
  routes/gallery.routes.js
Labels: backend, frontend

#65 Add SEO meta tags using Helmet
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Topic/TopicPage.jsx
  client/src/components/Words/Words.jsx
  client/src/pages/AboutMe/AboutMe.jsx
  client/src/pages/ContactMe/ContactMe.jsx
  client/src/pages/HomePage/HomePage.jsx
  client/src/pages/LoginPage/LoginPage.jsx
  client/src/pages/SignupPage/SignupPage.jsx
Labels: frontend
